# Generated by Django 6.0.3 on 2026-03-27 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='The name of the ingredient', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='The name of the recipe', max_length=255)),
                ('description', models.TextField(blank=True, help_text='A brief description of the recipe', null=True, verbose_name='Description')),
                ('difficulty', models.CharField(blank=True, choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], help_text='The difficulty level of the recipe (e.g., Easy, Medium, Hard)', max_length=50, null=True, verbose_name='Difficulty Level')),
                ('preparation_time', models.IntegerField(blank=True, help_text='The time required to prepare the recipe in minutes', null=True, verbose_name='Preparation Time (minutes)')),
                ('author', models.ForeignKey(help_text='The user who created the recipe', on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.CharField(blank=True, help_text='The quantity of the ingredient needed for the recipe (e.g., 2 cups, 1 tablespoon)', max_length=100, null=True, verbose_name='Quantity')),
                ('ingredient', models.ForeignKey(help_text='The ingredient used in the recipe', on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='kitchen.ingredient')),
                ('recipe', models.ForeignKey(help_text='The recipe that this ingredient belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='kitchen.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='My Shopping List', help_text='The name of the shopping list', max_length=255)),
                ('user', models.ForeignKey(help_text='The user who owns this shopping list', on_delete=django.db.models.deletion.CASCADE, related_name='shopping_lists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingListItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.CharField(blank=True, help_text='The quantity of the ingredient needed for the shopping list (e.g., 2 cups, 1 tablespoon)', max_length=100, null=True, verbose_name='Quantity')),
                ('ingredient', models.ForeignKey(help_text='The ingredient that needs to be purchased', on_delete=django.db.models.deletion.CASCADE, related_name='shopping_list_items', to='kitchen.ingredient')),
                ('shopping_list', models.ForeignKey(help_text='The shopping list that this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='kitchen.shoppinglist')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(help_text='A description of the step')),
                ('order', models.IntegerField(help_text='The order of the step in the recipe')),
                ('recipe', models.ForeignKey(help_text='The recipe that this step belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='kitchen.recipe')),
            ],
        ),
    ]
