# Generated by Django 6.0.3 on 2026-03-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(blank=True, choices=[('g', 'grams'), ('kg', 'kilograms'), ('ml', 'milliliters'), ('l', 'liters'), ('tsp', 'teaspoons'), ('tbsp', 'tablespoons'), ('cup', 'cups'), ('pcs', 'pieces')], help_text='The unit of measurement for the ingredient (e.g., grams, cups)', max_length=10, null=True, verbose_name='Unit'),
        ),
        migrations.AddField(
            model_name='shoppinglistitem',
            name='unit',
            field=models.CharField(blank=True, choices=[('g', 'grams'), ('kg', 'kilograms'), ('ml', 'milliliters'), ('l', 'liters'), ('tsp', 'teaspoons'), ('tbsp', 'tablespoons'), ('cup', 'cups'), ('pcs', 'pieces')], help_text='The unit of measurement for the ingredient (e.g., grams, cups)', max_length=10, null=True, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='quantity',
            field=models.IntegerField(blank=True, help_text='The quantity of the ingredient needed for the recipe (e.g., 2 cups, 1 tablespoon)', null=True, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='quantity',
            field=models.IntegerField(blank=True, help_text='The quantity of the ingredient needed for the shopping list (e.g., 2 cups, 1 tablespoon)', null=True, verbose_name='Quantity'),
        ),
    ]
