# Generated by Django 6.0.3 on 2026-03-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0002_recipeingredient_unit_shoppinglistitem_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='servings',
            field=models.IntegerField(blank=True, help_text='The number of servings the recipe makes', null=True, verbose_name='Servings'),
        ),
    ]
