# Generated by Django 6.0.3 on 2026-03-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0003_recipe_servings'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='timer',
            field=models.IntegerField(blank=True, help_text='The time in minutes that this step takes (optional)', null=True, verbose_name='Timer (minutes)'),
        ),
        migrations.AddField(
            model_name='step',
            name='used_ingredients',
            field=models.ManyToManyField(blank=True, help_text='The ingredients used in this step', related_name='steps', to='kitchen.ingredient'),
        ),
    ]
