# Generated by Django 6.0.3 on 2026-04-01 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0004_step_timer_step_used_ingredients'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='A brief biography of the user (optional)', null=True, verbose_name='Bio')),
                ('profile_picture', models.ImageField(blank=True, help_text='A profile picture for the user (optional)', null=True, upload_to='profile_pictures/', verbose_name='Profile Picture')),
                ('favorite_recipes', models.ManyToManyField(blank=True, help_text='The recipes that the user has marked as favorites', related_name='favorited_by', to='kitchen.recipe')),
                ('user', models.OneToOneField(help_text='The user that this profile belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
