# Generated by Django 6.0.3 on 2026-04-18 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0006_recipe_cooking_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='countable',
            field=models.BooleanField(default=True, help_text='Whether the ingredient is countable (e.g., 2 eggs) or uncountable (e.g., 200g flour)'),
        ),
    ]
