# Generated by Django 6.0.3 on 2026-04-26 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0007_ingredient_countable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglistitem',
            name='bought',
            field=models.BooleanField(default=False, help_text='Whether the item has been bought or not'),
        ),
        migrations.AddField(
            model_name='shoppinglistitem',
            name='custom_name',
            field=models.CharField(blank=True, help_text='Name for custom items that are not in the ingredient database (an item can have either an ingredient or a custom name, but not both)', max_length=255, null=True, verbose_name='Custom Name'),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='user',
            field=models.OneToOneField(help_text='The user who owns this shopping list', on_delete=django.db.models.deletion.CASCADE, related_name='shopping_lists', to=settings.AUTH_USER_MODEL),
        ),
    ]
