# Generated by Django 6.0.3 on 2026-05-01 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0008_shoppinglistitem_bought_shoppinglistitem_custom_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='unit',
            field=models.CharField(blank=True, choices=[('g', 'grams'), ('kg', 'kilograms'), ('ml', 'milliliters'), ('l', 'liters'), ('pcs', 'pieces')], help_text='The unit of measurement for the ingredient (e.g., grams, cups)', max_length=10, null=True, verbose_name='Unit'),
        ),
    ]
