# Generated by Django 6.0.3 on 2026-05-02 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0009_alter_shoppinglistitem_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='ingredient',
            field=models.ForeignKey(blank=True, help_text='The ingredient that needs to be purchased', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shopping_list_items', to='kitchen.ingredient'),
        ),
    ]
