# Generated by Django 6.0.3 on 2026-05-18 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0010_alter_shoppinglistitem_ingredient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_method',
            field=models.CharField(blank=True, choices=[('Baked', 'oven'), ('Stovetop', 'stovetop'), ('Microwaved', 'microwave'), ('No Cook', 'no-cook')], help_text='The cooking method used for the recipe (e.g., Baked, Stovetop, Microwaved, No Cook)', max_length=50, null=True, verbose_name='Cooking Method'),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='user',
            field=models.OneToOneField(help_text='The user who owns this shopping list', on_delete=django.db.models.deletion.CASCADE, related_name='shopping_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='unit',
            field=models.CharField(blank=True, choices=[('pcs', 'pieces'), ('g', 'grams'), ('kg', 'kilograms'), ('ml', 'milliliters'), ('l', 'liters')], help_text='The unit of measurement for the ingredient (e.g., grams, cups)', max_length=10, null=True, verbose_name='Unit'),
        ),
    ]
