# Generated by Django 6.0.3 on 2026-06-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0011_alter_recipe_cooking_method_alter_shoppinglist_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image_url',
            field=models.URLField(blank=True, help_text='A URL to an image of the finished dish (optional)', null=True, verbose_name='Image URL'),
        ),
    ]
