# Generated by Django 6.0.3 on 2026-07-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0013_alter_recipe_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.CharField(blank=True, choices=[('Meat', 'Meat'), ('Fish', 'Fish'), ('Vegetarian', 'Vegetarian'), ('Vegan', 'Vegan'), ('Dessert', 'Dessert'), ('Side', 'Side'), ('Starter', 'Starter'), ('Pasta', 'Pasta'), ('Breakfast', 'Breakfast')], help_text='The category of the recipe (e.g., Beef, Chicken, Dessert)', max_length=50, null=True, verbose_name='Category'),
        ),
    ]
