# Generated by Django 6.0.3 on 2026-08-06 07:19

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0014_recipe_category'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_lower_ingredient_name'),
        ),
    ]
