# Generated by Django 6.0.3 on 2026-08-07 06:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0015_ingredient_unique_lower_ingredient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image_asset',
            field=models.ImageField(blank=True, null=True, upload_to='dishes/', validators=[django.core.validators.validate_image_file_extension]),
        ),
    ]
