# Generated by Django 6.0.3 on 2026-08-08 06:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0016_recipe_image_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(blank=True, help_text='A brief description of the recipe', null=True, validators=[django.core.validators.MaxLengthValidator(1500)], verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='preparation_time',
            field=models.IntegerField(blank=True, help_text='The time required to prepare the recipe in minutes', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1440)], verbose_name='Preparation Time (minutes)'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='servings',
            field=models.IntegerField(blank=True, help_text='The number of servings the recipe makes', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Servings'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='quantity',
            field=models.FloatField(blank=True, help_text='The quantity of the ingredient needed for the recipe (e.g., 2 cups, 1 tablespoon)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='quantity',
            field=models.FloatField(blank=True, help_text='The quantity of the ingredient needed for the shopping list (e.g., 2 cups, 1 tablespoon)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='step',
            name='description',
            field=models.TextField(help_text='A description of the step', validators=[django.core.validators.MaxLengthValidator(1500)]),
        ),
        migrations.AlterField(
            model_name='step',
            name='order',
            field=models.IntegerField(help_text='The order of the step in the recipe', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='step',
            name='timer',
            field=models.IntegerField(blank=True, help_text='The time in minutes that this step takes (optional)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1440)], verbose_name='Timer (minutes)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='A brief biography of the user (optional)', null=True, validators=[django.core.validators.MaxLengthValidator(700)], verbose_name='Bio'),
        ),
        migrations.AddConstraint(
            model_name='shoppinglistitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('custom_name__isnull', True), ('ingredient__isnull', False)), models.Q(('custom_name__isnull', False), ('ingredient__isnull', True)), _connector='OR'), name='ingredient_or_custom_name'),
        ),
        migrations.AddConstraint(
            model_name='step',
            constraint=models.UniqueConstraint(fields=('recipe', 'order'), name='unique_step_order_per_recipe'),
        ),
    ]
