# Generated by Django 6.0.3 on 2026-08-08 10:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0017_alter_recipe_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='The date and time when the recipe was created'),
            preserve_default=False,
        ),
    ]
