# Generated by Django 6.0.3 on 2026-08-26 10:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0018_recipe_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes or tips for the recipe (optional)', null=True, validators=[django.core.validators.MaxLengthValidator(1500)], verbose_name='Notes'),
        ),
    ]
